// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = "https://mdfmjrcznydyyboergpx.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kZm1qcmN6bnlkeXlib2VyZ3B4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY0NTA4MTcsImV4cCI6MjA1MjAyNjgxN30.eza2os6UFN0oRwPnigDwxuNUT9Jl9jFHOVaB4I6fBRA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);